services:
  document-generator:
    image: opensemanticworld/document-generator
    build:
      context: ./
    container_name: document-generator
    restart: unless-stopped
    # volumes:
    #   - ./:/app
    # env_file:
    #   - .env
    # options see https://panel.holoviz.org/how_to/server/commandline.html
    command:
      - "/app/.venv/bin/python"
      - "src/document_generator/main.py"
    # For local testing only, comment out in production
    # ports:
    #   - "5010:5010"
